[api]
host = 'localhost'
port = 8000
project_name = 'base'

[database]
host='database'
port=5432
username='postgres'
password='postgres'
database='postgres'

[rabbitmq]
user = 'rabbitmq'
password = 'rabbitmq'
vhost = '/'
port = 5672
host = 'rabbitmq'


