version: "1.1"

services:
  user_microservice:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.user_microservice
    environment:
      CONFIG_PATH: /app/configs/config.toml
    ports:
      - "8000:8000"
    volumes:
      - ../user_microservice:/app/user_microservice:ro
      - ../user_microservice/infra/postgres/migration/versions:/app/user_microservice/infra/postgres/migration/versions:rw

  database:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
volumes:
  pgdata: