FROM python:3.12-slim AS user_microservice

WORKDIR /app

RUN apt-get update && apt-get install -y iproute2 iptables && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y iperf3
COPY pyproject.toml poetry.lock* /app/

COPY deploy/configs/config_user_microservice.toml /app/deploy/configs/

RUN pip install poetry

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root

COPY user_microservice /app/user_microservice

COPY deploy/entrypoint_user.sh /app/entrypoint_user.sh
RUN chmod +x /app/entrypoint_user.sh

ENTRYPOINT ["/app/entrypoint_user.sh"]
