FROM python:3.12-slim AS user_microservice

WORKDIR /app

COPY pyproject.toml poetry.lock* /app/

COPY deploy/configs/config_task_microservice.toml /app/deploy/configs/

RUN pip install poetry

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root

COPY task_microservice /app/task_microservice

CMD ["uvicorn", "task_microservice.main.web:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
