version: "1.1"

services:
  user_microservice:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.user_microservice
    environment:
      CONFIG_PATH: /app/configs/config_user_microservice.toml
      HOST: ${HOST}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    cap_add:
      - NET_ADMIN
    networks:
      app_network:
        ipv4_address: 172.20.0.10
    ports:
      - "8000:8000"
    volumes:
      - ../user_microservice:/app/user_microservice:ro
      - ../user_microservice/infra/postgres/migrations/versions:/app/user_microservice/infra/postgres/migrations/versions:rw
    labels:
      - "tier=backend"
      - "app=user_microservice"

  database:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      app_network:
        ipv4_address: 172.20.0.20
        aliases:
          - dbhost
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      app_network:
        ipv4_address: 172.20.0.5
        aliases:
          - dbhost
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  registration-api:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.registration
    container_name: registration-api
    ports:
      - "5000:5000"
      - "7000:7000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5000"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
      HOST: ${HOST}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      app_network:
        ipv4_address: 172.20.0.40
    volumes:
      - ../registration/Migrations:/app/registration/Migrations:rw
    cap_add:
      - NET_ADMIN
    labels:
      - "tier=backend"
      - "app=registration-api"


volumes:
  pgdata:
  pgadmin_data:

networks:
  app_network:
    external: true
    driver: bridge
    labels:
      env: dev
      project: my_app
    ipam:
      config:
        - subnet: 172.20.0.0/24