FROM mcr.microsoft.com/dotnet/sdk:9.0


RUN apt-get update && apt-get install -y iproute2 iptables && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y iperf3
WORKDIR /app

COPY registration/*.csproj ./registration/
WORKDIR /app/registration
RUN dotnet restore

COPY registration/. ./

RUN dotnet tool restore
RUN dotnet publish -c Release -o /app/publish

WORKDIR /app/publish

EXPOSE 5000
EXPOSE 7000

COPY deploy/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]